language: ruby
rvm:
- 2.2.6
gemfile:
- Gemfile.travis
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:migrate RAILS_ENV=test
- bundle exec rspec -fd spec/
deploy:
  api_key:
    secure: t6b2r7DdCU8oQcmo0Ff92AhdryYGDhq7r8XyzNGTHJGOqjupfLpRa2hAqEGSDPL7cbJ0InabFPsZJRSfh4wF1lPK9k2X1AH+7sfghgEor+CWceTjA6TojwGu14bF+LMwmATn1GjkZXbZNTO9v+9U9zyoQS9ZC//G8MxC9qKgBrFzcrSMnIz/DwirQKoOuKgcFWCtUNtotToWL7hZumF2LRbuIodPU8+l46AHyJUSS9/rYbeK/Cr/xABXkzXlnRMU0XJby7NpuJ73pUhoZk3T+9Ds39Yq0JntCZcW1nv4u0c9kvlHxcgM+7GDWzVtJIcUBWVHIIomioofyTIgxfnb49BLkUVM6Cgbm/sP7UjEzdE1TS8nP+p5Tgiq/iCC+5oEN0c4G2Z9uGNVBPgm/VFjgG7ffmPIV5WIuknxgmlvtVe8w1CUJZO+yvjwRiesfxvxOsvyKZeAuzgOzQ03oO9tXhAJaOI78muh75HU79956NFISXe044K+qLkhAFAorNz5rHD0cwU3Jnim55pqMqUovlvNXTXQch2zgJOeko0g8YjlLQtM7rXi9a6Xya2929+tRQcERMnxrGjLBgsFTIaZHMbFD8TXGIRZyLr5Pp9Ow5Y6Tb0spgFePPJOW8vMcCC9MNlrejOVIxTmla1Q3CuvJ+JtPp3A3G0IhY7NSBoRcRc=
run: "rake db:migrate"